// Compiles tokens.json to dist/tokens.css: CSS custom properties for light
// (default), dark via prefers-color-scheme, and explicit [data-theme] overrides.
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const t = JSON.parse(readFileSync(join(root, "tokens.json"), "utf8"));

function colorVars(mode) {
  const c = t.color[mode];
  const lines = [
    `--c-linen: ${c.linen};`,
    `--c-surface-raised: ${c.surfaceRaised};`,
    `--c-ink: ${c.ink};`,
    `--c-sage: ${c.sage};`,
    `--c-mist: ${c.mist};`,
    `--c-juniper: ${c.juniper};`,
  ];
  for (const [k, v] of Object.entries(c.state)) lines.push(`--c-state-${k}: ${v};`);
  c.speaker.forEach((v, i) => lines.push(`--c-speaker-${i + 1}: ${v};`));
  // Brand accents (e.g. the Claude connector CTA) — not part of the app palette.
  if (c.brand)
    for (const [k, v] of Object.entries(c.brand))
      lines.push(`--c-brand-${k.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase())}: ${v};`);
  return lines.join("\n  ");
}

const shared = [];
t.space.forEach((v, i) => shared.push(`--space-${i + 1}: ${v}px;`));
for (const [k, v] of Object.entries(t.radius)) shared.push(`--radius-${k}: ${typeof v === "number" ? v + "px" : v};`);
for (const [k, v] of Object.entries(t.elevation)) shared.push(`--elev-${k}: ${v};`);
for (const [k, v] of Object.entries(t.motion))
  shared.push(`--motion-${k.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase())}: ${typeof v === "number" ? v + "ms" : v};`);
shared.push(`--font-display: ${t.type.display};`);
shared.push(`--font-body: ${t.type.body};`);
shared.push(`--font-mono: ${t.type.mono};`);
for (const [k, s] of Object.entries(t.type.scale)) {
  const kk = k.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());
  shared.push(`--type-${kk}: ${s.weight} ${s.size}px/${s.line}px var(--font-${s.font});`);
}

const css = `/* GENERATED by @collective/tokens — do not edit by hand. */
:root {
  ${colorVars("light")}
  ${shared.join("\n  ")}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    ${colorVars("dark")}
  }
}
:root[data-theme="dark"] {
  ${colorVars("dark")}
}
@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-instant: 0ms;
    --motion-fast: 80ms;
    --motion-base: 100ms;
    --motion-slow: 100ms;
  }
}
`;

mkdirSync(join(root, "dist"), { recursive: true });
writeFileSync(join(root, "dist", "tokens.css"), css);
console.log("tokens.css written");
